const bcrypt = require('bcrypt-nodejs');

const pass = bcrypt.hashSync("test");

exports.seed = function(knex, Promise) {
  return Promise.all([
    // Inserts seed entries
    knex('users').insert([{
      "firstname": "Michael",
      "lastname": "Henderson",
      "username": "mhenderson0",
      "email": "mhenderson0@netscape.com",
      "password": bcrypt.hashSync("9i9WjJPPHF6Q"),
      "timezone": "Africa/Dar_es_Salaam"
    }, {
      "firstname": "Bobby",
      "lastname": "Thomas",
      "username": "bthomas1",
      "email": "bthomas1@symantec.com",
      "password": bcrypt.hashSync("67OtDms"),
      "timezone": "Asia/Manila"
    }, {
      "firstname": "Virginia",
      "lastname": "Carroll",
      "username": "vcarroll2",
      "email": "vcarroll2@cbc.ca",
      "password": bcrypt.hashSync('0H2c0Uu'),
      "timezone": "America/Tegucigalpa"
    }, {
      "firstname": "Linda",
      "lastname": "Alexander",
      "username": "lalexander3",
      "email": "lalexander3@youtu.be",
      "password": bcrypt.hashSync('SOODFZpll'),
      "timezone": "Europe/Lisbon"
    }, {
      "firstname": "David",
      "lastname": "Bailey",
      "username": "dbailey4",
      "email": "dbailey4@wunderground.com",
      "password": bcrypt.hashSync('IQ7SPDgA'),
      "timezone": "Europe/Volgograd"
    }, {
      "firstname": "Clarence",
      "lastname": "Castillo",
      "username": "ccastillo5",
      "email": "ccastillo5@time.com",
      "password": bcrypt.hashSync('sZUeXm2dvgX'),
      "timezone": "Europe/Warsaw"
    }, {
      "firstname": "Ashley",
      "lastname": "Hunt",
      "username": "ahunt6",
      "email": "ahunt6@princeton.edu",
      "password": bcrypt.hashSync('wbcwaE'),
      "timezone": "Europe/Prague"
    }, {
      "firstname": "Ruth",
      "lastname": "Hall",
      "username": "rhall7",
      "email": "rhall7@flickr.com",
      "password": bcrypt.hashSync('l95TqJ8ThS'),
      "timezone": "America/Tegucigalpa"
    }, {
      "firstname": "Julia",
      "lastname": "Palmer",
      "username": "jpalmer8",
      "email": "jpalmer8@whitehouse.gov",
      "password": bcrypt.hashSync('RBhW49Y'),
      "timezone": "Europe/Warsaw"
    }, {
      "firstname": "Kenneth",
      "lastname": "Ferguson",
      "username": "kferguson9",
      "email": "kferguson9@statcounter.com",
      "password": bcrypt.hashSync('gcldNT'),
      "timezone": "Asia/Harbin"
    }, {
      "firstname": "Cynthia",
      "lastname": "Franklin",
      "username": "cfranklina",
      "email": "cfranklina@howstuffworks.com",
      "password": bcrypt.hashSync('ijatNx5MmJl'),
      "timezone": "Indian/Maldives"
    }, {
      "firstname": "Helen",
      "lastname": "Murray",
      "username": "hmurrayb",
      "email": "hmurrayb@zdnet.com",
      "password": bcrypt.hashSync('fuZiVe8IKBL'),
      "timezone": "Europe/Tirane"
    }, {
      "firstname": "Jimmy",
      "lastname": "Green",
      "username": "jgreenc",
      "email": "jgreenc@toplist.cz",
      "password": bcrypt.hashSync('WexWqyPuy0'),
      "timezone": "America/Caracas"
    }, {
      "firstname": "Diane",
      "lastname": "Hunt",
      "username": "dhuntd",
      "email": "dhuntd@amazonaws.com",
      "password": bcrypt.hashSync('yPxiqnNi1'),
      "timezone": "Asia/Karachi"
    }, {
      "firstname": "Thomas",
      "lastname": "Murphy",
      "username": "tmurphye",
      "email": "tmurphye@slideshare.net",
      "password": bcrypt.hashSync('6MqA6wgGT'),
      "timezone": "Asia/Jakarta"
    }, {
      "firstname": "Tammy",
      "lastname": "Carroll",
      "username": "tcarrollf",
      "email": "tcarrollf@ning.com",
      "password": bcrypt.hashSync('GbRIFIri'),
      "timezone": "America/New_York"
    }, {
      "firstname": "Jacqueline",
      "lastname": "Kennedy",
      "username": "jkennedyg",
      "email": "jkennedyg@cbc.ca",
      "password": bcrypt.hashSync('UKMlZJUl'),
      "timezone": "America/Bogota"
    }, {
      "firstname": "Adam",
      "lastname": "Austin",
      "username": "aaustinh",
      "email": "aaustinh@google.it",
      "password": bcrypt.hashSync('GiXkMEX'),
      "timezone": "Asia/Manila"
    }, {
      "firstname": "Ashley",
      "lastname": "Gray",
      "username": "agrayi",
      "email": "agrayi@economist.com",
      "password": bcrypt.hashSync('OljTzTPc73gJ'),
      "timezone": "Asia/Singapore"
    }, {
      "firstname": "Sarah",
      "lastname": "Franklin",
      "username": "sfranklinj",
      "email": "sfranklinj@bigcartel.com",
      "password": bcrypt.hashSync('oEORP2Brne'),
      "timezone": "Europe/Stockholm"
    }])
  ]);
};
